---
title: "Curvature"
---

## Overview

One of the most salient parameters that can characterize the shape of a whisker is the degree of bending of the whisker when it encounters an object. For some line in space

## Methods

$k(x) = \frac{y''(x)}{(1 + (y'(x))^2)^\frac{3}{2}}$

### Direct Calculation via Finite Differences

Pros:

Simple

Cons:

Susceptible to noisy variation from point to point

central differences are poorly defined within unequal spacing between points

### 2nd Order Polynomial

Curvature is well defined for a parabola at any position x according to the following equation:

$k(x) = \frac{2a}{(1 + (2ax + b)^2)^\frac{3}{2})}$

Pros:

Leverages more points for calculation of curvature to reduce noise

Cons:

Parabola fit may be poor for some orientations of points.

The part of the parabola fitting the whiskers will change as the whisker moves. While the curvature is specified for any point along the parabola, there may be position-dependent fitting noise that results.

https://en.wikipedia.org/wiki/Curvature#Local_expressions

### Alternative Strategies (Not implemented):

#### Bezier Curve

#### Radius of Curvature of Circle

## Intrinsic Curvature and 𝝙𝛋

Whiskers are not straight, and generally have some natural bending at rest. Consequently, forces and moments generated in the follicular complex occur not because of the existence of curvature, but because of changes from the inherent curvature.

Note that as the whisker moves during whisking in air there is some true change in curvature of the whisker from its intrinsic position, as well as noise that results from measurement error in whisker parameterization, 3D whisker rotation in the 2D plane that is not accounted for.
