# Syntax: gitignore rules

# Ignore files and directories for all sections from gitignore file
# Default: True
gitignore-import-and-ignore: True

# Ignore files and directories for tree
# and "Contents of ..." sections
ignore-tree-and-content:
  - ".repo-to-text-settings.yaml"

ignore-content:
  - "LICENSE"
  - "tests/WhiskerTracking/data"
  - "scripts/"
  - "docs/"
