name: 'Linux Setup'
description: 'Setup common dependencies and environment for CI'
inputs:
  compiler:
    description: 'Compiler to use'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4

    - uses: seanmiddleditch/gha-setup-ninja@master

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install python dependencies Unix
      run: python -m pip install --upgrade pip pytest numpy

    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: "Install Linux System Dependencies"
      run: |
        sudo apt-get update
        sudo apt-get install -y libomp-18-dev lcov llvm gcovr

    - name: "Set environmental variables"
      shell: bash
      run: |
        echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV