---
title: "Curvature"
---

## Overview

One of the most salient parameters that can characterize the shape of a whisker is the degree of bending of the whisker when it encounters an object. For some line in space

## Methods

$k(x) = \frac{y''(x)}{(1 + (y'(x))^2)^\frac{3}{2}}$

### Direct Calculation via Finite Differences

Pros:

Simple

Cons:

Susceptible to noisy variation from point to point

central differences are poorly defined within unequal spacing between points

### 2nd Order Polynomial

Curvature is well defined for a parabola at any position x according to the following equation:

$k(x) = \frac{2a}{(1 + (2ax + b)^2)^\frac{3}{2})}$

https://en.wikipedia.org/wiki/Curvature#Local_expressions

### Bezier Curve

### Radius of Curvature of Circle

## Intrinsic Curvature and ğ™ğ›‹

Whiskers are not straight, and generally have some natural bending at rest. Consequently, forces and moments generated in the follicular complex occur not because of the existance of curvature, but because of changes from the inherent curvature.
