
project:
  type: website
  output-dir: .

website: 
  title: "Whisker Analysis"
  sidebar:
    style: docked
    contents: 
      - section: "Introduction"
        contents:
        - index.qmd
        
      - section: "Whisker Parameterization"
        contents:
        - parameterization/parameter_overview.qmd
        - parameterization/discretization.qmd
        - parameterization/mask.qmd
        - parameterization/follicle.qmd
        - parameterization/point.qmd
        - parameterization/quality_parameters.qmd
        - parameterization/beam_parameters.qmd
        
      - section: "Kinematics"
        contents:
        - kinematics_overview.qmd
        - angle.qmd
        - curvature.qmd
        - phase.qmd
        - velocity.qmd
        
      - section: "Mechanics"
        contents: 
        - mechanics_overview.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


