
project:
  type: website
  output-dir: .

website: 
  title: "Whisker Analysis"
  sidebar:
    style: docked
    contents: 
      - section: "Introduction"
        contents:
        - index.qmd
      - section: "Whisker Parameterization"
        contents:
        - discretization.qmd
        - mask.qmd
        - follicle.qmd
      - section: "Kinematics"
        contents:
        - angle.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


