
project:
  type: website
  output-dir: .

website: 
  title: "Whisker Analysis"
  sidebar:
    style: docked
    contents: 
      - section: "Introduction"
        contents:
        - index.qmd
        
      - section: "Tutorials"
      
      - section: "How-to Guides"
      
      - section: "Reference Guides"
      
      - section: "Background and Concepts"
        contents:
        
        - section: "Whisker Parameterization"
          contents:
          - parameterization/parameter_overview.qmd
          - parameterization/discretization.qmd
          - parameterization/mask.qmd
          - parameterization/follicle.qmd
          - parameterization/point.qmd
          - parameterization/quality_parameters.qmd
          - parameterization/beam_parameters.qmd
        
        - section: "Kinematics"
          contents:
          - kinematics/kinematics_overview.qmd
          - kinematics/angle.qmd
          - kinematics/curvature.qmd
          - kinematics/phase.qmd
          - kinematics/velocity.qmd
        
        - section: "Mechanics"
          contents: 
          - mechanics/mechanics_overview.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


