
project:
  type: website
  output-dir: .

website: 
  title: "Whisker Analysis"
  sidebar:
    style: docked
    contents: 
      - section: "Introduction"
        contents:
        - index.qmd
        
      - section: "Whisker Parameterization"
        contents:
        - discretization.qmd
        - mask.qmd
        - follicle.qmd
        - point.qmd
        - quality_parameters.qmd
        - beam_parameters.qmd
        
      - section: "Kinematics"
        contents:
        - angle.qmd
        - curvature.qmd
        - phase.qmd
        - velocity.qmd
        
      - section: "Mechanics"
        contents: 
        - mechanics_overview.qmd
     
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


