name: Benchmark Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - {"os": ubuntu-latest, short: linux, compiler: gcc, shell: bash}

    runs-on: ${{matrix.os}}

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    defaults:
      run:
        shell: '${{ matrix.shell }} {0}'

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/linux-setup
        with:
          compiler: ${{matrix.compiler}}

      - name: Configure CMake
        run: |
            cmake --preset ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Build
        run: cmake --build --preset ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Benchmark
        run:  ${{ github.workspace }}/out/build/GCC/Release/tests/benchmark | tee ${{ github.workspace }}/benchmark_result.txt
        working-directory: ${{ github.workspace }}/out/build/GCC/Release/tests

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Benchmark
          tool: 'catch2'
          output-file-path: benchmark_result.txt
          github-token: ${{ secrets.PAGES_TOKEN }}
          auto-push: true
          gh-pages-branch: gh-pages
          benchmark-data-dir-path: docs/dev/bench

      


