name: Linux Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        include:
          - {"os": ubuntu-latest, short: linux, compiler: gcc, shell: bash}
          - {"os": ubuntu-latest, short: linux, compiler: clang, shell: bash}

    runs-on: ${{matrix.os}}

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    defaults:
      run:
        shell: '${{ matrix.shell }} {0}'

    steps:
      - uses: actions/checkout@v4

      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'

      - name: Install python dependencies Unix
        run: python -m pip install --upgrade pip pytest numpy
        if: runner.os == 'Linux'

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: "Install Linux System Dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y libomp-18-dev lcov llvm gcovr

      - name: "Set environmental variables"
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - name: Configure CMake with coverage Linux GCC
        if: matrix.compiler == 'gcc'
        run: |
            cmake --preset ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}" -DCODE_COVERAGE=ON

      - name: Configure CMake without coverage for all other runners (does not equal gcc AND Linux)
        if: ${{ !(matrix.compiler == 'gcc') }}
        run: |
            cmake --preset ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Build
        run: cmake --build --preset ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Test
        run: ctest --verbose --preset ${{matrix.short}}-${{matrix.compiler}}-release -C ${{matrix.short}}-${{matrix.compiler}}-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"
        working-directory: ${{ github.workspace }}

      - name: Capture coverage info
        if: matrix.compiler == 'gcc'
        run: |
          lcov --directory /home/runner/work/Whisker-Analysis/Whisker-Analysis/out/build/GCC/Release --capture --output-file coverage.info
          lcov --remove coverage.info '/usr/*' '*/tests/*' '*/out/*' '*/opt/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload coverage to Coveralls
        if: matrix.compiler == 'gcc'
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.COVERALLS_REPO_TOKEN }}
          path-to-lcov: coverage.info
