name: Code-Checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for comparison

      - name: Common Setup
        uses: ./.github/actions/linux-setup
        with:
          buildfolder: out/build/Clang/Release
          compiler: clang

      - name: Install code-checker dependencies
        run: sudo apt-get update && sudo apt-get install -y cppcheck

      - name: Install Infer static analyzer
        run: |
          VERSION=1.2.0; \
          curl -SL "https://github.com/facebook/infer/releases/download/v$VERSION/infer-linux-x86_64-v$VERSION.tar.xz" \
          | sudo tar -C /opt -xJ && \
          sudo ln -s "/opt/infer-linux-x86_64-v$VERSION/bin/infer" /usr/local/bin/infer

      - name: Configure CMake without coverage
        run: cmake --preset linux-clang-release

      - name: Run Codechecker
        uses: whisperity/codechecker-analysis-action@v1
        id: codechecker
        with:
          logfile:  /home/runner/work/Whisker-Analysis/Whisker-Analysis/out/build/Clang/Release/compile_commands.json
          version: v6.25.1
          config: /home/runner/work/Whisker-Analysis/Whisker-Analysis/code-checker.json
          install-custom: true


      - name: Upload codechecker analysis
        uses: actions/upload-artifact@v4
        with:
          name: "CodeChecker Bug Reports"
          path: ${{ steps.codechecker.outputs.result-html-dir }}

