name: Clang-Tidy Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    defaults:
      run:
        shell: 'bash {0}'

    steps:
      - uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/linux-setup
        with:
          compiler: clang

      - name: "Install Linux System Dependencies"
        shell: bash
        run: |
            sudo apt-get update
            sudo apt-get install -y libyaml-dev

      - name: Install python dependencies Windows
        run: ppip --no-cache-dir install --verbose --force-reinstall -I pyyaml

      - name: Configure CMake without coverage
        run: |
            cmake --preset linux-clang-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Build
        run: cmake --build --preset linux-clang-release -DPython3_ROOT_DIR="${{ env.pythonLocation }}"

      - name: Download optview2
        run: git clone https://github/OfekShilon/optview2.git
        shell: bash

      - name: Run Optview2
        run: |
            mkdir opt_output
            optview2/opt-viewer.py --output-dir opt_output \
            --source-dir out/build/Clang/Release out/build/Clang/Release/src
            zip -r opt_output.zip opt_output

      - name: Upload Optimization Report Artifact
        uses: actions/upload-artifact@v4
        with:
            name: iwyu-report
            path: ${{ github.workspace }}/opt_output.zip
